settings:
  title: 'Status Page'
  url: 'https://mn.sfaka.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: herob
    name: heroku测试
    description: 'heroku测试' # default=empty
    url: 'https://herob.herokuapp.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: hybo
    name: 咱也不知道叫什么名字
    description: '咱也不知道叫什么名字'
    url: 'https://hybo.herokuapp.com'
    method: GET
    expectStatus: 200

